from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(407, 665)
        Dialog.setMinimumSize(QtCore.QSize(407, 665))
        Dialog.setMaximumSize(QtCore.QSize(407, 665))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.information_box = QtWidgets.QGroupBox(Dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.information_box.setFont(font)
        self.information_box.setObjectName("information_box")
        self.formLayout = QtWidgets.QFormLayout(self.information_box)
        self.formLayout.setObjectName("formLayout")
        self.default_part_text = QtWidgets.QLabel(self.information_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.default_part_text.setFont(font)
        self.default_part_text.setObjectName("default_part_text")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.default_part_text)
        self.good_part_text = QtWidgets.QLabel(self.information_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.good_part_text.setFont(font)
        self.good_part_text.setObjectName("good_part_text")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.good_part_text)
        self.good_part_data = QtWidgets.QLabel(self.information_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.good_part_data.setFont(font)
        self.good_part_data.setObjectName("good_part_data")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.good_part_data)
        self.default_count_text = QtWidgets.QLabel(self.information_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.default_count_text.setFont(font)
        self.default_count_text.setObjectName("default_count_text")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.default_count_text)
        self.default_count_data = QtWidgets.QLabel(self.information_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.default_count_data.setFont(font)
        self.default_count_data.setObjectName("default_count_data")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.default_count_data)
        self.good_count_text = QtWidgets.QLabel(self.information_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.good_count_text.setFont(font)
        self.good_count_text.setObjectName("good_count_text")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.good_count_text)
        self.good_count_data = QtWidgets.QLabel(self.information_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.good_count_data.setFont(font)
        self.good_count_data.setObjectName("good_count_data")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.good_count_data)
        self.border_scoring_text = QtWidgets.QLabel(self.information_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.border_scoring_text.setFont(font)
        self.border_scoring_text.setObjectName("border_scoring_text")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.border_scoring_text)
        self.border_scoring_data = QtWidgets.QLabel(self.information_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.border_scoring_data.setFont(font)
        self.border_scoring_data.setObjectName("border_scoring_data")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.border_scoring_data)
        self.border_bki_text = QtWidgets.QLabel(self.information_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.border_bki_text.setFont(font)
        self.border_bki_text.setObjectName("border_bki_text")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.SpanningRole, self.border_bki_text)
        self.border_bki_data = QtWidgets.QLabel(self.information_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.border_bki_data.setFont(font)
        self.border_bki_data.setObjectName("border_bki_data")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.border_bki_data)
        self.default_part_data = QtWidgets.QLabel(self.information_box)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.default_part_data.setFont(font)
        self.default_part_data.setObjectName("default_part_data")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.default_part_data)
        self.verticalLayout.addWidget(self.information_box)
        self.bki_box = QtWidgets.QGroupBox(Dialog)
        self.bki_box.setObjectName("bki_box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.bki_box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bki_data = QtWidgets.QLineEdit(self.bki_box)
        self.bki_data.setObjectName("bki_data")
        self.gridLayout_2.addWidget(self.bki_data, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.bki_box)
        self.scoring_box = QtWidgets.QGroupBox(Dialog)
        self.scoring_box.setObjectName("scoring_box")
        self.gridLayout = QtWidgets.QGridLayout(self.scoring_box)
        self.gridLayout.setObjectName("gridLayout")
        self.scoring_data = QtWidgets.QLineEdit(self.scoring_box)
        self.scoring_data.setObjectName("scoring_data")
        self.gridLayout.addWidget(self.scoring_data, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.scoring_box)
        self.default_proba_box = QtWidgets.QGroupBox(Dialog)
        self.default_proba_box.setObjectName("default_proba_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.default_proba_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.default_data = QtWidgets.QLineEdit(self.default_proba_box)
        self.default_data.setObjectName("default_data")
        self.gridLayout_3.addWidget(self.default_data, 0, 0, 1, 1)
        self.calculate_button = QtWidgets.QPushButton(self.default_proba_box)
        self.calculate_button.setObjectName("calculate_button")
        self.gridLayout_3.addWidget(self.calculate_button, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.default_proba_box)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.information_box.setTitle(_translate("Dialog", "Информация"))
        self.default_part_text.setText(_translate("Dialog", "Доля дефолтных заявок"))
        self.good_part_text.setText(_translate("Dialog", "Доля кредитоспособных заявок"))
        self.good_part_data.setText(_translate("Dialog", "0"))
        self.default_count_text.setText(_translate("Dialog", "Количество дефолтных заявок"))
        self.default_count_data.setText(_translate("Dialog", "0"))
        self.good_count_text.setText(_translate("Dialog", "Количество кредитоспособных заявок"))
        self.good_count_data.setText(_translate("Dialog", "0"))
        self.border_scoring_text.setText(_translate("Dialog", "Граница отсечения по скоринговому баллу"))
        self.border_scoring_data.setText(_translate("Dialog", "0"))
        self.border_bki_text.setText(_translate("Dialog", "Граница отсечения по баллу БКИ"))
        self.border_bki_data.setText(_translate("Dialog", "0"))
        self.default_part_data.setText(_translate("Dialog", "0"))
        self.bki_box.setTitle(_translate("Dialog", "Столбец балла БКИ"))
        self.scoring_box.setTitle(_translate("Dialog", "Столбец скорингового балла"))
        self.default_proba_box.setTitle(_translate("Dialog", "Вероятность дефолта"))
        self.calculate_button.setText(_translate("Dialog", "Вычислить"))
