from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(705, 409)
        dialog.setMinimumSize(QtCore.QSize(705, 409))
        dialog.setMaximumSize(QtCore.QSize(705, 409))
        self.type_box = QtWidgets.QGroupBox(dialog)
        self.type_box.setGeometry(QtCore.QRect(20, 10, 381, 71))
        self.type_box.setObjectName("type_box")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.type_box)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.select_type = QtWidgets.QComboBox(self.type_box)
        self.select_type.setMinimumSize(QtCore.QSize(351, 31))
        self.select_type.setObjectName("select_type")
        self.select_type.addItem("")
        self.select_type.addItem("")
        self.select_type.addItem("")
        self.gridLayout_4.addWidget(self.select_type, 0, 0, 1, 1)
        self.normalization_box = QtWidgets.QGroupBox(dialog)
        self.normalization_box.setGeometry(QtCore.QRect(20, 190, 381, 99))
        self.normalization_box.setObjectName("normalization_box")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.normalization_box)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.select_normalization = QtWidgets.QComboBox(self.normalization_box)
        self.select_normalization.setMinimumSize(QtCore.QSize(351, 31))
        self.select_normalization.setObjectName("select_normalization")
        self.select_normalization.addItem("")
        self.select_normalization.addItem("")
        self.select_normalization.addItem("")
        self.select_normalization.addItem("")
        self.select_normalization.addItem("")
        self.select_normalization.addItem("")
        self.gridLayout_6.addWidget(self.select_normalization, 0, 0, 1, 1)
        self.normalization_first = QtWidgets.QCheckBox(self.normalization_box)
        self.normalization_first.setMinimumSize(QtCore.QSize(171, 21))
        self.normalization_first.setObjectName("normalization_first")
        self.gridLayout_6.addWidget(self.normalization_first, 1, 0, 1, 1)
        self.standardization_box = QtWidgets.QGroupBox(dialog)
        self.standardization_box.setGeometry(QtCore.QRect(20, 100, 381, 71))
        self.standardization_box.setObjectName("standardization_box")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.standardization_box)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.select_standartization = QtWidgets.QComboBox(self.standardization_box)
        self.select_standartization.setMinimumSize(QtCore.QSize(351, 31))
        self.select_standartization.setObjectName("select_standartization")
        self.select_standartization.addItem("")
        self.select_standartization.addItem("")
        self.select_standartization.addItem("")
        self.select_standartization.addItem("")
        self.select_standartization.addItem("")
        self.gridLayout_5.addWidget(self.select_standartization, 0, 0, 1, 1)
        self.balance_box = QtWidgets.QGroupBox(dialog)
        self.balance_box.setGeometry(QtCore.QRect(20, 300, 381, 71))
        self.balance_box.setObjectName("balance_box")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.balance_box)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.select_balance = QtWidgets.QComboBox(self.balance_box)
        self.select_balance.setMinimumSize(QtCore.QSize(351, 31))
        self.select_balance.setObjectName("select_balance")
        self.select_balance.addItem("")
        self.select_balance.addItem("")
        self.select_balance.addItem("")
        self.select_balance.addItem("")
        self.gridLayout_7.addWidget(self.select_balance, 0, 0, 1, 1)
        self.input_data_box = QtWidgets.QGroupBox(dialog)
        self.input_data_box.setGeometry(QtCore.QRect(420, 100, 241, 121))
        self.input_data_box.setObjectName("input_data_box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.input_data_box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_data_text = QtWidgets.QTextEdit(self.input_data_box)
        self.input_data_text.setMinimumSize(QtCore.QSize(221, 71))
        self.input_data_text.setMaximumSize(QtCore.QSize(221, 71))
        self.input_data_text.setObjectName("input_data_text")
        self.gridLayout_2.addWidget(self.input_data_text, 0, 0, 1, 1)
        self.output_data_box = QtWidgets.QGroupBox(dialog)
        self.output_data_box.setGeometry(QtCore.QRect(420, 230, 241, 101))
        self.output_data_box.setObjectName("output_data_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.output_data_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.output_data_text = QtWidgets.QTextEdit(self.output_data_box)
        self.output_data_text.setMinimumSize(QtCore.QSize(221, 61))
        self.output_data_text.setMaximumSize(QtCore.QSize(221, 61))
        self.output_data_text.setObjectName("output_data_text")
        self.gridLayout_3.addWidget(self.output_data_text, 0, 0, 1, 1)
        self.create_button = QtWidgets.QPushButton(dialog)
        self.create_button.setGeometry(QtCore.QRect(420, 340, 241, 31))
        self.create_button.setObjectName("create_button")
        self.data_percent_box = QtWidgets.QGroupBox(dialog)
        self.data_percent_box.setGeometry(QtCore.QRect(420, 10, 241, 71))
        self.data_percent_box.setObjectName("data_percent_box")
        self.gridLayout = QtWidgets.QGridLayout(self.data_percent_box)
        self.gridLayout.setObjectName("gridLayout")
        self.data_percent = QtWidgets.QSpinBox(self.data_percent_box)
        self.data_percent.setMinimumSize(QtCore.QSize(217, 31))
        self.data_percent.setMaximumSize(QtCore.QSize(217, 31))
        self.data_percent.setObjectName("data_percent")
        self.gridLayout.addWidget(self.data_percent, 0, 0, 1, 1)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Создание модели"))
        self.type_box.setTitle(_translate("dialog", "Тип модели"))
        self.select_type.setItemText(0, _translate("dialog", "Логистическая регрессия"))
        self.select_type.setItemText(1, _translate("dialog", "Наивный байес. классификатор"))
        self.select_type.setItemText(2, _translate("dialog", "Решающее дерево"))
        self.normalization_box.setTitle(_translate("dialog", "Нормализация данных"))
        self.select_normalization.setItemText(0, _translate("dialog", "Без нормализации"))
        self.select_normalization.setItemText(1, _translate("dialog", "Минимакс нормализация"))
        self.select_normalization.setItemText(2, _translate("dialog", "Нормализация алгебраической функцией"))
        self.select_normalization.setItemText(3, _translate("dialog", "Нормализация обобщенной алгебраической функцией"))
        self.select_normalization.setItemText(4, _translate("dialog", "Нормализация обобщенным вариантом сигмоиды"))
        self.select_normalization.setItemText(5, _translate("dialog", "Нормализация арктангенсом"))
        self.normalization_first.setText(_translate("dialog", "Сначала нормализация"))
        self.standardization_box.setTitle(_translate("dialog", "Стандартизация данных"))
        self.select_standartization.setItemText(0, _translate("dialog", "Без стандартизации"))
        self.select_standartization.setItemText(1, _translate("dialog", "Метод Парето"))
        self.select_standartization.setItemText(2, _translate("dialog", "Z-преобразование"))
        self.select_standartization.setItemText(3, _translate("dialog", "Масштабирование стабильности переменной"))
        self.select_standartization.setItemText(4, _translate("dialog", "Степенное преобразование"))
        self.balance_box.setTitle(_translate("dialog", "Балансировка классов"))
        self.select_balance.setItemText(0, _translate("dialog", "Без балансировки"))
        self.select_balance.setItemText(1, _translate("dialog", "Дублирование миноритарных примеров"))
        self.select_balance.setItemText(2, _translate("dialog", "SMOTE (синтетические примеры)"))
        self.select_balance.setItemText(3, _translate("dialog", "Удаление мажоритарных примеров"))
        self.input_data_box.setTitle(_translate("dialog", "Входные данные"))
        self.input_data_text.setHtml(_translate("dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.input_data_text.setPlaceholderText(_translate("dialog", "Индексы столбцов входных данных без пробелов, через запятую"))
        self.output_data_box.setTitle(_translate("dialog", "Выходные данные"))
        self.output_data_text.setHtml(_translate("dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.output_data_text.setPlaceholderText(_translate("dialog", "Индекс столбца выходных данных"))
        self.create_button.setText(_translate("dialog", "Создать модель"))
        self.data_percent_box.setTitle(_translate("dialog", "Размер обучающей выборки"))
        self.data_percent.setSpecialValueText(_translate("dialog", "В процентах"))
