from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(599, 631)
        MainWindow.setMinimumSize(QtCore.QSize(583, 624))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.data_box = QtWidgets.QGroupBox(self.centralwidget)
        self.data_box.setMinimumSize(QtCore.QSize(561, 551))
        self.data_box.setObjectName("data_box")
        self.gridLayout = QtWidgets.QGridLayout(self.data_box)
        self.gridLayout.setObjectName("gridLayout")
        self.table_view = QtWidgets.QTableView(self.data_box)
        self.table_view.setObjectName("table_view")
        self.gridLayout.addWidget(self.table_view, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.data_box, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 599, 26))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.model_menu = QtWidgets.QMenu(self.menubar)
        self.model_menu.setObjectName("model_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.select_file = QtWidgets.QAction(MainWindow)
        self.select_file.setObjectName("select_file")
        self.create_model = QtWidgets.QAction(MainWindow)
        self.create_model.setObjectName("create_model")
        self.model_metrics = QtWidgets.QAction(MainWindow)
        self.model_metrics.setObjectName("model_metrics")
        self.model_borders = QtWidgets.QAction(MainWindow)
        self.model_borders.setObjectName("model_borders")
        self.save_model = QtWidgets.QAction(MainWindow)
        self.save_model.setObjectName("save_model")
        self.file_menu.addAction(self.select_file)
        self.model_menu.addAction(self.create_model)
        self.model_menu.addSeparator()
        self.model_menu.addAction(self.model_borders)
        self.model_menu.addAction(self.model_metrics)
        self.model_menu.addAction(self.save_model)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.model_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Анализ заемщиков"))
        self.data_box.setTitle(_translate("MainWindow", "Данные"))
        self.file_menu.setTitle(_translate("MainWindow", "Файл"))
        self.model_menu.setTitle(_translate("MainWindow", "Модель"))
        self.select_file.setText(_translate("MainWindow", "Выбрать..."))
        self.create_model.setText(_translate("MainWindow", "Создать"))
        self.model_metrics.setText(_translate("MainWindow", "Метрики модели"))
        self.model_borders.setText(_translate("MainWindow", "Границы отсечения"))
        self.save_model.setText(_translate("MainWindow", "Сохранить результат"))
